// <auto-generated />
using CP5_JogosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CP5_JogosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CP5_JogosAPI.Models.Desenvolvedora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoFundacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisOrigem")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Desenvolvedoras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoFundacao = 1994,
                            Nome = "CD Projekt Red",
                            PaisOrigem = "Polônia"
                        },
                        new
                        {
                            Id = 2,
                            AnoFundacao = 1986,
                            Nome = "FromSoftware",
                            PaisOrigem = "Japão"
                        },
                        new
                        {
                            Id = 3,
                            AnoFundacao = 1983,
                            Nome = "Nintendo EPD",
                            PaisOrigem = "Japão"
                        });
                });

            modelBuilder.Entity("CP5_JogosAPI.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DesenvolvedoraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double>("Nota")
                        .HasColumnType("REAL");

                    b.Property<string>("Plataforma")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DesenvolvedoraId");

                    b.ToTable("Jogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoLancamento = 2015,
                            DesenvolvedoraId = 1,
                            Genero = "RPG",
                            Nota = 9.8000000000000007,
                            Plataforma = "PC",
                            Preco = 79.90m,
                            Titulo = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 2,
                            AnoLancamento = 2022,
                            DesenvolvedoraId = 2,
                            Genero = "Souls-like",
                            Nota = 9.5999999999999996,
                            Plataforma = "PS5",
                            Preco = 249.90m,
                            Titulo = "Elden Ring"
                        },
                        new
                        {
                            Id = 3,
                            AnoLancamento = 2023,
                            DesenvolvedoraId = 3,
                            Genero = "Aventura",
                            Nota = 9.6999999999999993,
                            Plataforma = "Switch",
                            Preco = 299.90m,
                            Titulo = "The Legend of Zelda: Tears of the Kingdom"
                        });
                });

            modelBuilder.Entity("CP5_JogosAPI.Models.Jogo", b =>
                {
                    b.HasOne("CP5_JogosAPI.Models.Desenvolvedora", "Desenvolvedora")
                        .WithMany("Jogos")
                        .HasForeignKey("DesenvolvedoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Desenvolvedora");
                });

            modelBuilder.Entity("CP5_JogosAPI.Models.Desenvolvedora", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
